export const EXT_TO_PRISM: Record<string, string> = {
  js:       'javascript',
  mjs:      'javascript',
  cjs:      'javascript',
  jsx:      'jsx',
  ts:       'typescript',
  tsx:      'tsx',
  py:       'python',
  rb:       'ruby',
  rs:       'rust',
  go:       'go',
  java:     'java',
  cs:       'csharp',
  cpp:      'cpp',
  cc:       'cpp',
  cxx:      'cpp',
  hpp:      'cpp',
  c:        'c',
  h:        'c',
  php:      'php',
  swift:    'swift',
  kt:       'kotlin',
  kts:      'kotlin',
  sh:       'bash',
  bash:     'bash',
  zsh:      'bash',
  sql:      'sql',
  graphql:  'graphql',
  json:     'json',
  yaml:     'yaml',
  yml:      'yaml',
  xml:      'xml',
  svg:      'xml',
  html:     'html',
  htm:      'html',
  css:      'css',
  scss:     'scss',
  sass:     'scss',
  toml:     'toml',
  md:       'markdown',
  mdx:      'markdown',
  log:      'plaintext',
  logs:     'plaintext',
  txt:      'plaintext',
}

export function detectLanguage(filename: string): string | undefined {
  const ext = filename.split('.').pop()?.toLowerCase() ?? ''
  return EXT_TO_PRISM[ext]
}
